server:
  port: 8091

enrolltournament:
  version: 1
  
spring:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "shuffle2149@gmail.com"
    password: "rsapzkolnfowyxad"
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false

  liquibase:
    change-log: 'db/changelog/db.changelog-master.xml'
    enabled: true

  storage:
    location: '/home/shuffle/java/storage'

  datasource:
  url: "jdbc:mysql://localhost:3306/nsk_tt?createDatabaseIfNotExist=true&
  allowPublicKeyRetrieval=true&useSSL=false&
  useUnicode=true&
  characterEncoding=UTF-8&serverTimezone=UTC"
  username: "admin"
  password: "qwertyuiop"
  #url: "jdbc:mysql://localhost:3306/tt_Nsk"

---
spring:
  profiles: dev

  datasource:
    url: "jdbc:mysql://localhost:3306/nsk_tt?createDatabaseIfNotExist=true&
    allowPublicKeyRetrieval=true&useSSL=false&
    useUnicode=true&
    characterEncoding=UTF-8&serverTimezone=UTC"
    username: "root"
    password: "root"

storage:
  location: '/home/sergei/IdeaProjects/tt_nsk/storage'

---

spring:
  profiles: prod

  datasource:
    url: "jdbc:mysql://localhost:3306/nsk_tt?createDatabaseIfNotExist=true&
    allowPublicKeyRetrieval=true&useSSL=false&
    useUnicode=true&
    characterEncoding=UTF-8&serverTimezone=UTC"
    username: "shuffle"
    password: "shuffle"

storage:
  location: 'C:\Users\79130\storage'

---





