
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nsk_tt"
    username: "shuffle"
    password: "shuffle"
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

storage:
  #  location: '/home/shuffle/java/storage'
  #  location: 'C:\Users\79130\storage'
  location: 'C:\Users\79130\IdeaProjects\tt_nsk\storage'

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true

server:
#  hostname: 127.0.0.1
  port: 8092


