#spring:
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: false
#    generate-ddl: false
#  mail:
#    host: "smtp.gmail.com"
#    port: 587
#    username: "shuffle2149@gmail.com"
#    password: "rsapzkolnfowyxad"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    url: "jdbc:mysql://localhost:3306/nsk_tt?createDatabaseIfNotExist=true&
#    allowPublicKeyRetrieval=true&useSSL=false&
#    useUnicode=true&
#    characterEncoding=UTF-8&serverTimezone=UTC"
#    username: "shuffle"
#    password: "shuffle"
#
#  #    url: "jdbc:mysql://localhost:3306/tt_Nsk"
#  #    username: "admin"
#  #    password: "qwertyuiop"
#
#  liquibase:
#    change-log: db/changelog/db.changelog-master.xml
#    enabled: true
#
#storage:
#  location: 'C:\Users\79130\storage'
#
#servlet:
#  multipart:
#    max-file-size: 10MB
#    max-request-size: 10MB
#    enabled: true
#
#server:
#  #  hostname: site
#  port: 8093
#
