server:
  port: 8091

spring:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "shuffle2149@gmail.com"
    password: "rsapzkolnfowyxad"
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

#spring:
#  profiles:
#    active: "dev"
#  main:
#    banner-mode: "off"



---
spring:
  profiles:
    active: dev
  liquibase:
    change-log: 'db/changelog/db.changelog-master.xml'
    enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    generate-ddl: false

  datasource:
    url: "jdbc:mysql://localhost:3306/nsk_tt?createDatabaseIfNotExist=true&
    allowPublicKeyRetrieval=true&useSSL=false&
    useUnicode=true&
    characterEncoding=UTF-8&serverTimezone=UTC"
    username: "root"
    password: "root"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

storage:
  location: '/home/sergei/IdeaProjects/tt_nsk/storage'

---







