
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/nsk_tt"
#    username: "shuffle"
#    password: "shuffle"
#  liquibase:
#    change-log: db/changelog/db.changelog-master.xml
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        #default_schema: nsk_tt1
    generate-ddl: false
    #database-platform: nsk_tt1
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "shuffle2149@gmail.com"
    password: "rsapzkolnfowyxad"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:

    url: "jdbc:mysql://localhost:3306/nsk_tt?createDatabaseIfNotExist=true&
    allowPublicKeyRetrieval=true&useSSL=false&
    useUnicode=true&
    characterEncoding=UTF-8&serverTimezone=UTC"
    username: "shuffle"
    password: "shuffle"
storage:
  #  location: '/home/shuffle/java/storage'
  #  location: 'C:\Users\79130\storage'
  location: 'C:\Users\79130\IdeaProjects\tt_nsk\storage'

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true

server:
#  hostname: 127.0.0.1
  port: 8092


