#server:
#  port: 8090
#
#spring:
#  profiles:
#    active: ${SPRING_PROFILES_INCLUDE:tt-nsk}
#  config:
#    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
#  cloud:
#    config:
#      label: ${SPRING_CLOUD_CONFIG_LEVEL:master}
#      username: ${SPRING_CLOUD_CONFIG_USERNAME:user}
#      password: ${SPRING_CLOUD_CONFIG_PASSWORD:pass}
#
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nsk_tt"
    username: "shuffle"
    password: "shuffle"
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
#  mvc:
#    static-path-pattern: '/storage/players/**'

# Для ручного управления безопастностью (http://shuffle:shuffle@localhost:8080/player)
#  security:
#    user:
#      name: 'shuffle'
#      password: 'shuffle'
storage:
  location: './storage'

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true

server:
  port: 8091


