spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nsk_tt"
    username: "shuffle"
    password: "shuffle"
# Для ручного управления безопастностью (http://shuffle:shuffle@localhost:8080/player)
#  security:
#    user:
#      name: 'shuffle'
#      password: 'shuffle'
storage:
  location:
    './storage'

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true

